WIP: Allow building for multiple platforms (zynq and zynqmp)
PandABlocks/PandABlocks-server pull request #10
Opened 2021-05-15 00:28 UTC by hir12111

We are using a more standard ARM toolchain (from ARM), which required minor tweaks.
The variable PLATFORM can be `zynq` or `zynqmp`  to select the platform. The toolchain is configured via the variable TOOLCHAIN_ROOT.
Here is an example CONFIG:
```
TOOLCHAIN_ROOT = /dls_sw/targetOS/x-tools/gcc-10.2.1-glibc-2.31/$(COMPILER_PREFIX)
PANDA_ROOTFS = /dls_sw/work/panda2xu5/PandABlocks-rootfs
KERNEL_DIR = /scratch/tmp/PandA-rootfs-zynqmp/build/linux
PLATFORM = zynqmp
```

2021-05-19 13:39 UTC, Araneidae commented
Do we need the performance counter support at all now?  @thomascobb , what do you think?  Am inclined to drop it altogether.

2021-05-19 13:51 UTC, thomascobb commented
What is the performance counter?

2021-05-20 07:05 UTC, Araneidae commented
Can this branch be merged with the current build system?  In other words, do we need to wait for  [PandABlocks-FPGA#33](https://github.com/PandABlocks/PandABlocks-FPGA/pull/33) and  [PandABlocks-rootfs#18](https://github.com/dls-controls/rootfs)?

I am persuaded that `slow_load` should remain in this repository, which obviously affects [PandABlocks-FPGA](https://github.com/PandABlocks/PandABlocks-FPGA).

2021-05-20 07:08 UTC, hir12111 commented
Yes, you are right, this can be used with the current toolchain (as well as the new toolchain).
And slow_load will work for both platforms. I don't think there is any breaking change at all.

2021-05-20 07:09 UTC, hir12111 commented
The CONFIG changes a bit, but I don't think that's a problem

2021-05-20 07:12 UTC, Araneidae commented
I agree.  @thomascobb, can you see any reason not to merge this into master right away?

2021-05-20 07:13 UTC, Araneidae commented
Oh!  If the `CONFIG` file needs to change then you need to update `CONFIG.example` accordingly.

2021-05-20 07:23 UTC, Araneidae requested changes
The only change that's needed is `CONFIG.example`.

2021-05-20 07:39 UTC, hir12111 commented on Makefile
> +PLATFORM = $(error Define PLATFORM in CONFIG file)
Done

2021-05-20 07:58 UTC, Araneidae commented
Had to get the `CONFIG` just right to build with the old toolchain:
```bash
PYTHON = dls-python
COMPILER_PREFIX = arm-xilinx-linux-gnueabi
BINUTILS_DIR = /dls_sw/FPGA/Xilinx/SDK/2015.1/gnu/arm/lin
PLATFORM = zynq
DEFAULT_TARGETS = server sim_server docs
```
but it seems to build and pass its tests just fine.  Am happy to merge this.

2021-05-20 07:58 UTC, merged

2021-05-20 07:59 UTC, Araneidae commented
It seems confusing to have a `dls-controls` fork of this repository!

2021-05-20 09:18 UTC, thomascobb commented
@hir12111 I have sent you an invite to the PandABlocks org so you can push directly to branches in PandABlocks-* repos. Please can you start working on branches in this org and delete the dls-controls forks?

2021-05-20 09:28 UTC, Araneidae commented
Thanks for this @thomascobb, I was getting a bit confused by this!